# .github/workflows/build.yml
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # ------------------ VVVV 在这里添加新步骤 VVVV ------------------
    - name: List files in the repository
      run: ls -R
    # ------------------ ^^^^ 在这里添加新步骤 ^^^^ ------------------

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build # 注意：这里暂时用 build，而不是 :app:build
